= Introduction
:page-topic-type: concept
:page-toclevels: 2

[abstract]
The Couchbase Spark Connector provides first-class integration between your high performance Couchbase cluster and the Apache Spark data processing platform, and can be used from both Scala and PySpark.

Please see one of the following getting started guide:

* xref:getting-started.adoc[Scala getting started].
* xref:pyspark.adoc[PySpark getting started].
* xref:java-api.adoc[Java getting started].

The Couchbase Spark Connector supports any type of Couchbase cluster.  Users of Capella Columnar should see the xref:columnar.adoc[Columnar Support] page.

== Compatibility

Every version of the Couchbase Spark connector is compiled against a specific Apache Spark target.

E.g. if you are using Apache Spark 3.5.x, you should use a 3.5.x version of the Couchbase Spark Connector.

.Couchbase Spark Connector compatibility
|===
| Couchbase Spark Connector version | Apache Spark target version

| 3.5.x
| 3.5.x

| 3.3.x
| 3.3.x

| 3.2.x
| 3.2.x

| 3.1.x
| 3.1.x

| 3.0.x
| 3.0.x

|===

Note that if the internal Spark APIs do not break between minor versions, it is possible to use different version combinations.
The table above shows the combination Couchbase tests and supports.

=== Interface Stability

include::7.6@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]


== Contributing

Couchbase welcomes community contributions to the Spark connector.
The https://github.com/couchbase/couchbase-spark-connector[Spark connector source code^] is available on GitHub and contains instructions to contribute.
