= Introduction
:page-topic-type: concept
:page-toclevels: 2

[abstract]
The Couchbase Spark Connector provides first-class integration between your high performance Couchbase cluster and the Apache Spark data processing platform, and can be used from both Scala and PySpark.

Please see one of the following getting started guide:

* xref:getting-started.adoc[Scala getting started].
* xref:pyspark.adoc[PySpark getting started].
* xref:java-api.adoc[Java getting started].

The Couchbase Spark Connector supports any type of Couchbase cluster.  Users of Capella Columnar should see the xref:columnar.adoc[Columnar Support] page.

== Compatibility

=== Apache Spark 4.x users
From the 4.0.0 release, the Couchbase Spark Connector is changing release models to better accommodate the https://spark.apache.org/versioning-policy.html[upcoming changes to the Apache Spark release model].

Apache Spark now aim to release one major each year (N.0.0), followed by two feature minor releases (N.1.0 and N.2.0), then one long-term support (LTS) release N.3.0.
This will be adopted fully from 5.0.0, and is being transitioned to mid-major with the upcoming Apache Spark 4.3.0 release.

The connector will now also have one major each year, with connector 4.X releases (2026/27) corresponding to the Apache Spark 4.X major, and connector 5.x releases (expected 2027/28) for Apache Spark 5.x, etc.

Each 4.x connector release will aim where possible to be compatible with a useful subset of Apache Spark 4.x releases, particularly the latest patch of each minor that is currently supported by Apache.
Apache plan to support N.0.0, N.1.0 and N.2.0 for 6 months apiece, and the LTS N.3.0 for 18 months.  The connector will aim to follow the same support model.

See the xref:release-notes.adoc[release notes] for details of which Apache Spark versions are tested and fully supported for each connector release.
Users may try Apache Spark 4.x releases that are not listed there, though untested combinations will not be officially supported.

=== Apache Spark 3.5 users
Apache Spark 3.5.x users should use the latest 3.5.x of the Couchbase Spark Connector.

=== Interface Stability

include::7.6@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]

== Contributing

Couchbase welcomes community contributions to the Spark connector.
The https://github.com/couchbase/couchbase-spark-connector[Spark connector source code^] is available on GitHub and contains instructions to contribute.
