= Release Notes
:page-topic-type: concept

[abstract]
Release notes for the Couchbase Spark Connector.

== Couchbase Spark Connector 4.0.0 (20th August 2026)
From this 4.0.0 release, the Couchbase Spark Connector is changing release models to better accommodate the [upcoming changes to the Apache Spark release model](https://spark.apache.org/versioning-policy.html).

Apache Spark now aim to release one major each year (N.0.0), followed by two feature minor releases (N.1.0 and N.2.0), then one long-term support (LTS) release N.3.0.
This will be adopted fully from 5.0.0, and is being transitioned to mid-major with the upcoming Apache Spark 4.3.0 release.

The connector will now also have one major each year, with connector 4.X releases (2026/27) corresponding to the Apache Spark 4.X major, and connector 5.x releases (expected 2027/28) for Apache Spark 5.x, etc.

Each 4.x connector release will aim where possible to be compatible with a useful subset of Apache Spark 4.x releases, particularly the latest patch of each minor that is currently supported by Apache.
Apache plan to support N.0.0, N.1.0 and N.2.0 for 6 months apiece, and the LTS N.3.0 for 18 months.  The connector will aim to follow the same support model.

This connector release was built against these versions:

[cols="1,1"]
|===
| Dependency | Version

| Scala
| 2.13.18

| Spark (build profile 4.1)
| 4.1.3

| Hadoop
| 3.4.2

| Jackson
| 2.21.2

| Jackson annotations
| 2.21

| Couchbase operational SDK
| 3.12.2

| Couchbase Enterprise Analytics SDK
| 1.1.0
|===

Spark versions actively tested:

[cols="1,1,1,1,1"]
|===
| Profile | Spark | Hadoop | Jackson | Jackson annotations

| 4.1
| 4.1.3
| 3.4.2
| 2.21.2
| 2.21

| 4.2
| 4.2.0
| 3.5.0
| 2.21.2
| 2.21

|===

The support matrix for Apache Spark releases is:

[cols="1,1,2"]
|===
| Apache Spark version | Supported by Apache until | Status

| 4.3 and above
| -
| Currently unreleased; status unknown

| 4.2.0
| 2028-01-11
| Tested and supported

| 4.1.3
| 2027-07-11
| Tested and supported

| 4.0.X
| 2026-11-23
| Untested and unsupported; may not work due to very low Jackson version (2.18.2) Spark 4.0 uses

| 3.X
| -
| Does not work due to Apache Spark binary changes at 4.x
|===

The source of the Apache support dates is the community site [endoflife.date](https://endoflife.date/apache-spark) along with the [Apache Spark versioning policy](https://spark.apache.org/versioning-policy.html).

Users may try Apache Spark 4.x releases that are not listed here, though untested combinations will not be officially supported.

The 4.x series is built exclusively with Scala 2.13.

There are no changes to functionality in this 4.0.0 connector release.  It simply provides compatibility with Apache Spark 4.X.

== Couchbase Spark Connector 3.5.5 (4 August 2026)

Version 3.5.5 is built and tested against Spark 3.5.9, and supports Scala 2.12 and 2.13.
The only change from 3.5.4 is to bump all dependencies, include the underlying Couchbase Scala SDK which is now 3.12.2.

== Couchbase Spark Connector 3.3.7 (10 September 2025)
Important: most users should use the 3.5 series of the Spark Connector, which is compatible with Apache Spark 3.5.

This 3.3.7 connector release is for users of Apache Spark 3.3.  It is built and tested against Spark 3.3.4.

=== New Features
* https://couchbasecloud.atlassian.net/browse/SPARKC-232[SPARKC-232]:
KV DataFrame sub-document write support added.  See xref:subdocument.adoc[these docs] for more information.


== Couchbase Spark Connector 3.5.4 (19 November 2025)

Version 3.5.4 is built and tested against Spark 3.5.7, and supports Scala 2.12 and 2.13.

=== New Features
* https://couchbasecloud.atlassian.net/browse/SPARKC-232[SPARKC-232]:
KV DataFrame sub-document write support added.  See xref:subdocument.adoc[these docs] for more information.

== Couchbase Spark Connector 3.3.7 (10 September 2025)
Important: most users should use the 3.5 series of the Spark Connector, which is compatible with Apache Spark 3.5.

This 3.3.7 connector release is for users of Apache Spark 3.3.  It is built and tested against Spark 3.3.4.

=== New Features
* https://couchbasecloud.atlassian.net/browse/SPARKC-232[SPARKC-232]:
KV DataFrame sub-document write support added.  See xref:subdocument.adoc[these docs] for more information.

== Couchbase Spark Connector 3.5.3 (8 August 2025)

Version 3.5.3 is built and tested against Spark 3.5.6, and supports Scala 2.12 and 2.13.

The main feature in this release is support for Couchbase Enterprise Analytics.

=== New Features

* https://couchbasecloud.atlassian.net/browse/SPARKC-235[SPARKC-235]:
Support Enterprise Analytics.
* https://couchbasecloud.atlassian.net/browse/SPARKC-233[SPARKC-233]:
Add CAS to query DataFrame reads and KV DataFrame writes.
* https://couchbasecloud.atlassian.net/browse/SPARKC-231[SPARKC-231]:
Add KV replace support for DataFrame writes
* https://couchbasecloud.atlassian.net/browse/SPARKC-230[SPARKC-230]:
Add failure reporting and handling for individual operations.

=== Bug fixes
* https://couchbasecloud.atlassian.net/browse/SPARKC-213[SPARKC-213]:
`couchbase.query` write with `SaveMode.Ignore` throwing unexpected `DocumentExistsException`.

== Couchbase Spark Connector 3.3.6 (June 2025)
Important: most users should use the 3.5 series of the Spark Connector, which is compatible with Apache Spark 3.5.  

This 3.3.6 connector release is for users of Apache Spark 3.3 and primarily backports several important performance improvements from the 3.5 series.
It also adds some useful new features, which will be made available in the 3.5 series in a future release.

Version 3.3.6 is built and tested against Spark 3.3.4, and uses Couchbase Scala SDK 1.8.2 internally.

=== New Features
* https://couchbasecloud.atlassian.net/browse/SPARKC-231[SPARKC-231]:
Add KV replace support for DataFrame writes
* https://couchbasecloud.atlassian.net/browse/SPARKC-196[SPARKC-196]:
Support authentication with client certificates.
See xref:configuration.adoc[Client Certificates] for more information.
* https://couchbasecloud.atlassian.net/browse/SPARKC-230[SPARKC-230]:
Add failure reporting and handling for individual operations.
* https://couchbasecloud.atlassian.net/browse/SPARKC-233[SPARKC-233]:
Add CAS to query DataFrame reads and KV DataFrame writes.

=== Improvements
* https://couchbasecloud.atlassian.net/browse/SPARKC-212[SPARKC-212]:
Better distribute query read partitions so they are all approximately the same size, resulting in a performance improvement.
* https://couchbasecloud.atlassian.net/browse/SPARKC-209[SPARKC-209]:
Limits are now pushed down in DataFrame query reads, for a performance improvement.
* https://couchbasecloud.atlassian.net/browse/SPARKC-207[SPARKC-207]:
Many improvements to logging, with the most useful lines now logged at INFO rather than DEBUG.

=== Bugs
* https://couchbasecloud.atlassian.net/browse/SPARKC-210[SPARKC-210]:
Fixes a 3.3.4 regression that caused each read query to stream significantly slower.
* https://couchbasecloud.atlassian.net/browse/SPARKC-211[SPARKC-211]:
Fixes a 3.3.4 regression that caused each read query to get executed twice.
* https://couchbasecloud.atlassian.net/browse/SPARKC-206[SPARKC-206]:
Fixes query read partitioning not working with aggregation operations such as groupBy and count.


== Couchbase Spark Connector 3.5.2 (12 December 2024)

Version 3.5.2 is built and tested against Spark 3.5.3, and supports Scala 2.12 and 2.13.

This release focuses on the performance of query DataFrame reads (`spark.read.format("couchbase.query")`), with several major performance improvements resulting.
All users are encouraged to upgrade to this version.

=== Improvements
* https://couchbasecloud.atlassian.net/browse/SPARKC-212[SPARKC-212]:
Better distribute query read partitions so they are all approximately the same size, resulting in a performance improvement.
* https://couchbasecloud.atlassian.net/browse/SPARKC-209[SPARKC-209]:
Limits are now pushed down in DataFrame query reads, for a performance improvement.
* https://couchbasecloud.atlassian.net/browse/SPARKC-208[SPARKC-208]:
Move to Spark 3.5.3.
* https://couchbasecloud.atlassian.net/browse/SPARKC-207[SPARKC-207]:
Many improvements to logging, with the most useful lines now logged at INFO rather than DEBUG.

=== Bugs
* https://couchbasecloud.atlassian.net/browse/SPARKC-210[SPARKC-210]:
Fixes a 3.3.4 regression that caused each read query to stream significantly slower.
* https://couchbasecloud.atlassian.net/browse/SPARKC-211[SPARKC-211]:
Fixes a 3.3.4 regression that caused each read query to get executed twice.
* https://couchbasecloud.atlassian.net/browse/SPARKC-206[SPARKC-206]:
Fixes query read partitioning not working with aggregation operations such as groupBy and count.

== Couchbase Spark Connector 3.5.1 (4 September 2024)

Version 3.5.1 is built and tested against Spark 3.5.1, and supports Scala 2.12 and 2.13.

=== Improvements

* https://issues.couchbase.com/browse/SPARKC-196[SPARKC-196]:
Support authentication with client certificates.
See xref:configuration.adoc[Client Certificates] for more information.

== Couchbase Spark Connector 3.5.0 GA (9 August 2024)

Version 3.5.0 is built and tested against Spark 3.5.1, and supports Scala 2.12 and 2.13.

This is the first version of the connector to support Spark 3.5 and Scala 2.13.
It also adds support for xref:pyspark.adoc[PySpark] at `Stability.Volatile` level, and xref:columnar.adoc[Capella Columnar] at `Stability.Uncommitted` level.

=== Improvements

* https://issues.couchbase.com/browse/SPARKC-184[SPARKC-184]:
Support Spark 3.5.
* https://issues.couchbase.com/browse/SPARKC-185[SPARKC-185]:
Support Scala 2.13.
* https://issues.couchbase.com/browse/SPARKC-203[SPARKC-203]:
Support Capella Columnar.


== Couchbase Spark Connector 3.3.5 GA (30 July 2024)

Version 3.3.5 is built and tested against Spark 3.3.4.

=== Improvements

* https://issues.couchbase.com/browse/SPARKC-194[SPARKC-194]:
Partitioning options added for DataFrame query reads.


== Couchbase Spark Connector 3.3.4 GA (8 January 2024)

Version 3.3.4 is built and tested against Spark 3.3.4.

=== Bug fixes and stability

* https://issues.couchbase.com/browse/SPARKC-181[SPARKC-181]:
When performing a DataFrame read (`spark.read().format("couchbase.query")`), rows will now be streamed and backpressured, rather than buffered in-memory.


== Couchbase Spark Connector 3.3.3 GA (14 November 2023)

Version 3.3.3 is built and tested against Spark 3.3.0.

=== Bug fixes and stability

* https://issues.couchbase.com/browse/SPARKC-181[SPARKC-181]:
Allow structured streaming to work against clusters that do not have the KV service running on all nodes.


== Couchbase Spark Connector 3.3.2 GA (10 October 2023)

Version 3.3.2 is built and tested against Spark 3.3.0.

=== Bug fixes and stability

* https://issues.couchbase.com/browse/SPARKC-178[SPARKC-178]:
Fix issues with `connectionIdentifier`.


== Couchbase Spark Connector 3.3.1 GA (22 February 2023)

Version 3.3.1 is built and tested against Spark 3.3.0.

=== Bug fixes and stability

* https://issues.couchbase.com/browse/SPARKC-177[SPARKC-177]:
If alternate addresses are configured on the cluster (for instance, for Kubernetes deployments), these will now be used automatically when doing structured streaming.


== Couchbase Spark Connector 3.3.0 GA (January 2023)

Version 3.3.0 is the first version to support Spark 3.3.0.

=== Bug fixes and stability

* https://issues.couchbase.com/browse/SPARKC-166[SPARKC-166]:
Improved handling of aggregate result datatypes.
* https://issues.couchbase.com/browse/SPARKC-176[SPARKC-176]:
Bump DCP client version.
* https://issues.couchbase.com/browse/SPARKC-174[SPARKC-174]:
Adjust default DCP bootstrap timeout to improve connection capability in high-latency environments.

=== Features

* https://issues.couchbase.com/browse/SPARKC-167[SPARKC-167],
https://issues.couchbase.com/browse/SPARKC-168[SPARKC-168]:
Support connecting to multiple Clusters.
* https://issues.couchbase.com/browse/SPARKC-175[SPARKC-175],
https://issues.couchbase.com/browse/SPARKC-165[SPARKC-165]:
Support Spark 3.3.0.
* https://issues.couchbase.com/browse/SPARKC-160[SPARKC-160]:
Shade Reactor dependency into 'fatjar' build to better support the Databricks environment.



== Couchbase Spark Connector 3.2.2 GA (July 2022)

Version 3.2.2 is the third version to support Spark 3.2.x and is built on top of the Couchbase Scala SDK 1.3.x as well
as the Java DCP Client.

=== Features

* https://issues.couchbase.com/browse/SPARKC-157[SPARKC-157^]: Add support for "ignore" variants for KeyValue insert, replace and remove operations. This has been available in the Spark Connector 2.x series and has not been ported forward until this point.
* https://issues.couchbase.com/browse/SPARKC-159[SPARKC-159^]: TLS configuration is now more flexible. TLS can be enabled trough couchbases:// in the connection string, as well as being more robust in accepting certail security config parameters.
* https://issues.couchbase.com/browse/SPARKC-160[SPARKC-160^]: To avoid classpath issues in the Databricks notebook environment, the
Reactor library is now shaded in the assembly jar that is available for download. The regular jar still has the unshaded version of Reactor.

=== Bug fixes and stability

* https://issues.couchbase.com/browse/SPARKC-158[SPARKC-158^]: Open the implicitBucket if set for cluster-level operations. This
makes sure that cluster-level operations like N1QL queries can be performed against Couchbase Server clusters pre 6.5.


== Couchbase Spark Connector 3.2.1 GA (May 2022)

Version 3.2.1 is the second version to support Spark 3.2.x and is built on top of the Couchbase Scala SDK 1.3.x as well
as the Java DCP Client.

=== Features

* Updated the underlying SDK to 1.3.0, which (along with general enhancements and fixes) bundles the Capella certificate, so it doesn't have to be added manually.
* https://issues.couchbase.com/browse/SPARKC-133[SPARKC-133^]: Added support for spark structured streaming. For more details, see the documentation section for streaming.


== Couchbase Spark Connector 3.2.0 GA (January 2022)

Version 3.2.0 is the first version to support Spark 3.2.x and is built on top of the Couchbase Scala SDK 1.2.x.

=== Features

* Support for Apache Spark 3.2.x
* https://issues.couchbase.com/browse/SPARKC-146[SPARKC-146^]: Added support for scope-level Query and Analytics RDDs (through `Keyspace`)
* https://issues.couchbase.com/browse/SPARKC-148[SPARKC-148^]: Added support for aggregate pushdown for Query DataFrames.
* https://issues.couchbase.com/browse/SPARKC-148[SPARKC-149^]: Added support for aggregate pushdown for Analytics DataFrames.

=== Bug fixes and stability

* https://issues.couchbase.com/browse/SPARKC-143[SPARKC-143^]: Allow passing timeouts to KV, Query and Analytics DataFrame as option.
* https://issues.couchbase.com/browse/SPARKC-151[SPARKC-151^]: Fix ScanConsistency not being applied for Analytics and Query DataFrames.
* https://issues.couchbase.com/browse/SPARKC-144[SPARKC-144^], https://issues.couchbase.com/browse/SPARKC-145[SPARKC-145^]: Move Jackson JSON handling into the connector. This solves issues in the databricks notebook environment.
* https://issues.couchbase.com/browse/SPARKC-153[SPARKC-153^]: Properly escape fields for Analytics and Query DataFrames.


== Couchbase Spark Connector 3.1.0 GA (September 2021)

Version 3.1.0 is the first version to support Spark 3.1.x and is built on top of the Couchbase Scala SDK 1.1.x.

This release contains identical features to the Spark 3.0.0 connector, the only difference being compiled against Spark 3.1.x. Please refer to the 3.0 migration guide for changes and new features over 2.4.x.

=== Highlights

* Support for Apache Spark 3.1.x



== Couchbase Spark Connector 3.0.0 GA (September 2021)

Version 3.0.0 is the first version to support Spark 3.0.x and is built on top of the Couchbase Scala SDK 1.1.x.

Please note that this release does not have separate release notes, rather refer to the migration guide page for more information.

=== Highlights

* Support for Apache Spark 3.0.x
* Built on top of the new Scala SDK 1.2.x
* Support for Couchbase Server 7.0 and later




== Couchbase Spark Connector 2.4.1 GA (November 2020)

Version 2.4.1 brings support for Couchbase Cloud as well as:

=== Features

* https://issues.couchbase.com/browse/SPARKC-110[SPARKC-110^]: Allow passthrough of timestampFormat and dateFormat for inferring schema
* Updated the Java SDK to 2.7.18
* Allows enabling DNS SRV via a configuration property

=== Bug fixes and stability

* https://issues.couchbase.com/browse/SPARKC-104[SPARKC-104^]: Stopping and restarting of Spark-Couchbase-Streaming-job throws ClassCastException
* Properly propagate the expiry into the `DefaultSource`


== Couchbase Spark Connector 2.4.0 GA (July 2019)

Version 2.4.0 brings support for Spark 2.4.0, and is compiled exclusively with Scala 2.12.




== Couchbase Spark Connector 2.3.0 GA (May 2019)

Version 2.3.0 brings support for Spark 2.3.0 along with:

=== Features

* https://issues.couchbase.com/browse/SPARKC-93[SPARKC-93^]: Support for Apache Spark 2.3.0
* https://issues.couchbase.com/browse/SPARKC-89[SPARKC-89^]: Support Analytics
* https://issues.couchbase.com/browse/SPARKC-88[SPARKC-88^]: Allow N1QL queries to run on Spark node(s) co-located with query service
* https://issues.couchbase.com/browse/SPARKC-96[SPARKC-96^]:
Provide more fault-tolerant batch mutations.
`saveToCouchbase` now takes a `maxConcurrent` parameter, giving the application control over the size of batches that will be written, from each executor.

=== Bug fixes and stability

* https://issues.couchbase.com/browse/SPARKC-85[SPARCK-85^]: Raise N1QL errors as exceptions rather than logging them.
* https://issues.couchbase.com/browse/SPARKC-82[SPARKC-82^]:
When running a N1QLQuery, if multiple buckets have been specified, then the bucket to use must now be explicitly chosen.
E.g. `sc.couchbaseQuery(query, bucketName = "default")`.  This is safer than choosing an arbitrary bucket.
* https://issues.couchbase.com/browse/SPARKC-95[SPARKC-95^]: Fix to get streaming source working with Spark 2.3




== Couchbase Spark Connector 2.2.0 GA (September 2017)

Version 2.2.0 is the first stable release of the 2.2.x series.
It brings support for Spark 2.2 and the following enhancements and bugfixes:

=== Spark Core

* Support for Apache Spark 2.2.0
* https://issues.couchbase.com/browse/SPARKC-80[SPARKC-80^]: Support for Couchbase Server 5.0 and Role-Based Access Control
* https://issues.couchbase.com/browse/SPARKC-77[SPARKC-77^]: Global and per-operation timeout configuration is now possible
* https://issues.couchbase.com/browse/SPARKC-44[SPARKC-44^]: Support for Subdocument Mutations has been added.
* https://issues.couchbase.com/browse/SPARKC-79[SPARKC-79^]: Support for easier SSL/TLS configuration via spark config.

=== Spark SQL

* https://issues.couchbase.com/browse/SPARKC-77[SPARKC-77^]: per-operation timeout configuration is now possible

=== Spark Streaming

No changes for Spark Streaming have been made in this release.



== Older Releases

Although https://www.couchbase.com/support-policy/enterprise-software[no longer supported],
documentation for older releases continues to be available in our https://docs-archive.couchbase.com/home/index.html[docs archive].
