= DataFrames, Datasets, and SQL
:page-topic-type: concept
:description: Spark allows accessing query, analytics, Enterprise Analytics, and Capella Columnar in powerful and convenient ways.


[abstract]
{description}

While Apache's low-level xref:working-with-rdds.adoc[RDDs] are powerful, Apache Spark now encourages users towards the higher-level DataFrames and Datasets.
Let's see how to use those with Couchbase.

Before you can create DataFrames or Datasets with Couchbase, you need to create a `SparkSession`.
See xref:getting-started.adoc[Getting Started (Scala)] or xref:pyspark.adoc[Getting Start(PySpark)]

== Running examples
All query examples presented on this page at least require the `travel-sample` dataset to be installed on your Couchbase cluster, with a primary index.
If you haven't done so already, you can create a primary index by executing this {sqlpp} statement: `pass:c[CREATE PRIMARY INDEX ON `travel-sample`]`.

To use the operational analytics examples, corresponding datasets or collection mappings should be created.

Enterprise Analytics is also supported, and provides enhanced analytics capabilities for enterprise environments.

== DataFrames

A read `DataFrame` can be created through `spark.read.format(...)`, and which format to choose depends on the type of service you want to use.
For `spark.read`, `couchbase.query`, `couchbase.analytics`, `couchbase.enterprise-analytics`, and `couchbase.columnar` are available.

(For reading from the KV service - see xref:working-with-rdds.adoc[RDDs])

[{tabs}]
====
Scala::
+
[source,scala]
----
include::example$SparkSQL.scala[tag=simpledf,indent=0]
----
PySpark::
+
[source,python]
----
include::example$DataFrames.py[tag=simpledf,indent=0]
----
====

=== Collections

You'll generally want the DataFrame to work with a specific Couchbase collection, which can be done with the following:
[{tabs}]
====
Scala::
+
[source,scala]
----
include::example$SparkSQL.scala[tag=query-collection,indent=0]
----
PySpark::
+
[source,python]
----
include::example$DataFrames.py[tag=query-collection,indent=0]
----
Scala (Columnar)::
+
--
[source,scala]
----
include::example$SparkSQL.scala[tag=columnar-collection,indent=0]
----
--
Scala (Enterprise Analytics)::
+
--
[source,scala]
----
include::example$SparkSQL.scala[tag=enterprise-analytics-collection,indent=0]
----
--
PySpark (Enterprise Analytics)::
+
--
[source,python]
----
include::example$DataFrames.py[tag=enterprise-analytics-collection,indent=0]
----
--
====

Note all query options are documented here xref:_query_options[Query Options], all Capella Columnar options here xref:_columnar_options[Capella Columnar options], and all Enterprise Analytics options here xref:_enterprise_analytics_options[Enterprise Analytics options].

If you will usually be using the same collection, it can be more convenient to provide it in the SparkSession config instead:

[source,scala]
----
include::example$SparkSQL.scala[tag=context-with-all-implicit-options,indent=0]
----


[#_schemas]
=== Schemas

Spark requires a schema for all DataFrame and Dataset operations.

The Couchbase Spark Connector will perform automatic schema inference based on a random sampling of all documents in the chosen collection -- or bucket if no collection was chosen.
This automatic inference can work well in cases where the data are very similar.

If the data are not similar, there are two options: you can either provide a manual schema, or narrow down what documents the automatic schema inference acts on by providing explicit predicates.

For example, say the schema of the `airlines` collection evolves and we add a `"version": 2` field to identify documents that have the new schema.
We can limit both the inference and the {sqlpp} executed from the DataFrame to only those documents, by providing a filter:

[{tabs}]
====
Scala (Columnar)::
+
[source,scala]
----
include::example$SparkSQL.scala[tag=queryfilter,indent=0]
----
PySpark (Columnar)::
+
[source,python]
----
include::example$DataFrames.py[tag=queryfilter,indent=0]
----
Scala (Enterprise Analytics)::
+
[source,scala]
----
include::example$SparkSQL.scala[tag=enterprise-analytics-filter,indent=0]
----
PySpark (Enterprise Analytics)::
+
[source,python]
----
include::example$DataFrames.py[tag=enterprise-analytics-filter,indent=0]
----
====

You can call `airlines.printSchema()` to view the schema (either inferred or provided manually):

----
root
 |-- __META_ID: string (nullable = true)
 |-- callsign: string (nullable = true)
 |-- country: string (nullable = true)
 |-- iata: string (nullable = true)
 |-- icao: string (nullable = true)
 |-- id: long (nullable = true)
 |-- name: string (nullable = true)
 |-- type: string (nullable = true)
----

Not only did it automatically infer the schema, it also added a `META_ID` field which corresponds to the document ID if applicable.

A manual schema can also be provided, and this is the recommended practice for production applications, to protect against future data changes:

[{tabs}]
====
Scala::
+
[source,scala]
----
include::example$SparkSQL.scala[tag=manualschema,indent=0]
----
====

=== DataFrame Operations

Now that you have a DataFrame, you can apply all the operations that Spark SQL provides.
A simple example would be to load specific fields from the DataFrame and print some of those records:


[{tabs}]
====
Scala::
+
[source,scala]
----
include::example$SparkSQL.scala[tag=simplesort,indent=0]
----
PySpark::
+
[source,python]
----
include::example$DataFrames.py[tag=simplesort,indent=0]
----
====

Results in:
----
+-------+--------------------+
|   name|            callsign|
+-------+--------------------+
|   EASY|             easyJet|
|   BABY|             bmibaby|
|MIDLAND|                 bmi|
|   null|          Yellowtail|
|   null|               XOJET|
|STARWAY|   XL Airways France|
|   XAIR|            XAIR USA|
|  WORLD|       World Airways|
|WESTERN|    Western Airlines|
|   RUBY|Vision Airlines (V2)|
+-------+--------------------+
----

=== Spark SQL

We can use Spark's `createOrReplaceTempView` to create a temporary view from a DataFrame, which we can then run Spark SQL on (which creates another DataFrame):


[{tabs}]
====
Scala::
+
[source,scala]
----
include::example$Columnar.scala[tag=sql,indent=0]
----
PySpark::
+
[source,python]
----
include::example$DataFrames.py[tag=sql,indent=0]
----
====

Note this SQL is executed purely within Spark, and is not sent to the Couchbase cluster.

[#_dataframe_partitioning]
== DataFrame partitioning

By default, one DataFrame read or write with query will result in one {sqlpp} statement being executed.

With very large DataFrames this can present issues, as all rows are streamed back to one Spark worker.
In addition there is no parallelism.

So in some specific situations the user may wish to provide partitioning hints so that multiple {sqlpp} statements are executed.

In this example, say we are reading from an orders collection, where we know we have around 100,000 orders and want to partition into 100 {sqlpp} statements.
Here we will partition on a numerical "id" column:

[{tabs}]
====
Scala::
+
[source,scala]
----
include::example$SparkSQL.scala[tag=partitioning,indent=0]
----
PySpark::
+
[source,python]
----
include::example$DataFrames.py[tag=partitioning,indent=0]
----
====

This will result in 100 partitions with {sqlpp} statements along the lines of
```
SELECT [...] WHERE [...] AND id < 1000
SELECT [...] WHERE [...] AND (id >= 1000 AND id < 2000)
SELECT [...] WHERE [...] AND (id >= 2000 AND id < 3000)
...
SELECT [...] WHERE [...] AND id >= 99000
```

If any of the four partitioning options is provided, then all must be.

The chosen partitionColumn must support the SQL comparison operators "<" and ">=".
Any results where partitionColumn is null or otherwise not matched by those operators, will not be included.

`PartitionLowerBound` and `PartitionUpperBound` do not bound or limit the results, they simply choose how many results are in each partition.
Note that the first and last queries in the example above use `<` and `>=` to include all results.

=== Partitioning performance tips
When using query partitioning, users are often interested in obtaining the highest throughput possible.
Internal testing has found these tips will provide the best possible performance:

* Duplicating or replicating the GSI indexes used by the query, so that multiple query nodes are not bottlenecked by going to a single GSI node.
* Increasing the data service reader and writer threads.
* Ensuring the disks used can provide sufficient throughput/IOPS.
* Increasing the number of Couchbase nodes, and the resources (cores, memory, disk) allocated to each.
* Increasing the count of Spark worker nodes, and the number of cores on each (each core can execute one partition at a time).
* Ensuring sufficient network bandwidth is available.

[#_dataframe_persistence]
== DataFrame persistence

It is also possible to write DataFrames into Couchbase.

Couchbase documents require unique document ids, so this needs to be available in the DataFrame.
By default the connector will look for a `META_ID` column, but this can be overridden with an option (see below).

All the other fields in the DataFrame will be converted into JSON and stored as the document content.

You can store `DataFrames` using both `couchbase.query` and `couchbase.kv`.
We recommend using the KeyValue data source since it provides better performance out of the box if the usage pattern allows for it.

The following example reads data from a collection and writes the first 5 results into a different collection.
Also, to showcase properties, they are used on both the read and the write side:


[{tabs}]
====
Scala::
+
[source,scala]
----
include::example$SparkSQL.scala[tag=kvwrite,indent=0]
----
PySpark::
+
[source,python]
----
include::example$DataFrames.py[tag=kvwrite,indent=0]
----
====

And to specify your own document id column for a DataFrame `df`:


[{tabs}]
====
Scala::
+
[source,scala]
----
include::example$SparkSQL.scala[tag=writing,indent=0]
----
PySpark::
+
[source,python]
----
include::example$DataFrames.py[tag=writing,indent=0]
----
====

Note all key-value options are documented here xref:_kv_options[Key-Value options] and all query options are documented here xref:_query_options[Query Options].

=== Customising persistence

Spark has four built-in https://spark.apache.org/docs/latest/api/java/index.html?org/apache/spark/sql/SaveMode.html[SaveModes] that can be used to control how data is written into Couchbase.

As these Spark SaveModes do not cover all Couchbase functionality, the Couchbase Spark Connector additionally has a `KeyValueOptions.WriteMode` option.

This example shows the two in use:

[source,scala]
----
include::example$SparkSQL.scala[tag=savemode,indent=0]
----

The modes are mapped as follows:

.couchbase.kv mappings
|===
| SaveMode | Underlying Couchbase KV Operation | Behaviour

| SaveMode.Overwrite
| Upsert
| Document will be created if it does not exist

| SaveMode.ErrorIfExists
| Insert
| Operations will fail with `DocumentExistsException` if doc already exists

| SaveMode.Ignore
| Insert
| If the document already exists, that operation will be skipped

| SaveMode.Append
| _not supported_
|

| WriteModeReplace
| Replace
| Operations will fail with `DocumentNotFoundException` if doc does not exist

| WriteModeSubdocUpsert
| mutateIn (sub-document) with StoreSemantics.Upsert
| Document will be created if it does not exist

| WriteModeSubdocInsert
| mutateIn (sub-document) with StoreSemantics.Insert
| Operations will fail with `DocumentExistsException` if doc already exists

| WriteModeSubdocReplace
| mutateIn (sub-document) with StoreSemantics.Replace
| Operations will fail with `DocumentNotFoundException` if doc does not exist



|===

.couchbase.query mappings
|===
| SaveMode | Couchbase {sqlpp}

| SaveMode.Overwrite
| UPSERT INTO

| SaveMode.ErrorIfExists
| INSERT INTO

| SaveMode.Ignore
| INSERT INTO (Ignores `DocumentExistsException`)

| SaveMode.Append
| _not supported_

|===

=== Failure handling during persistence
The default is that the failure of any individual operation will fail the overall job.

For key-value DataFrame writes, this can be overridden with two error handling options.

`KeyValueOptions.ErrorBucket` will cause any operation failure to write a document back into a Couchbase collection, containing information identifying the failing document and the failure reason.
This is the recommended approach.

`KeyValueOptions.ErrorHandler` will call an error handling callback.
An example implementation of the interface is provided with the connector, and users are free to write their own also.

Refer to the Spark `KeyValueOptions` API documentation for further information.

=== Safe DataFrame persistence
Couchbase supports optimistic concurrency via CAS for query DataFrame reads and key-value DataFrame writes, which can be used with the Couchbase Spark Connector as shown:

[source,scala]
----
include::example$SparkSQL.scala[tag=cas,indent=0]
----

This protects against documents being modified between the read and write points.
Such modifications will cause the operation to fail with a `CasMismatchException`.
This will by default also cause the job to fail, which can be configured with the error handling options detailed elsewhere.

Couchbase supports optimistic concurrency via CAS for query DataFrame reads and key-value DataFrame writes, which can be used with the Couchbase Spark Connector as shown:

[source,scala]
----
include::example$SparkSQL.scala[tag=cas,indent=0]
----

This protects against documents being modified between the read and write points.
Such modifications will cause the operation to fail with a `CasMismatchException`.
This will by default also cause the job to fail, which can be configured with the error handling options detailed elsewhere.


=== Sub-document DataFrame KV persistence
Couchbase supports sub-document writes that update only specific parts of the document, and users writing large documents may find this provides a performance optimisation, or allows concurrent actors to modify different parts of the same documents.
The Spark Connector exposes the sub-document writes via both xref:working-with-rdds.adoc[RDDs] and DataFrames.

The connector will ultimately perform sub-document KV mutateIn calls, one for each row/document in the DataFrame.

For a mutateIn call, up to 16 sub-document 'specs' can be provided.  A spec has three elements:

- A spec operation.  All sub-document spec operations are supported by the connector: upsert, insert, replace, remove, arrayAppend, arrayPrepend, arrayInsert, arrayAddUnique, increment and decrement.
- A path where the operation acts, such as `user.name` (the `name` field of the `user` object), or `user.addresses[1]`.
- A value, which can be any valid JSON value.  This is written to the path.

For Spark, the core idea is that the DataFrame be setup by the application so that:

- Each row represents a single document (as standard).  Each row will be written with a single mutateIn KV call by the Spark connector.
- Each column represents a sub-document spec to be performed by every mutateIn call.  The column title combines the operation type and the path it acts on with format "operation:path" e.g. "upsert:user.name".  The "upsert:" prefix is optional, as that is the default.
- Each cell represents the value that will be written by a spec to a document.

An example will help make this clear.  Here we take an incoming DataFrame, manipulate it to specify the sub-document specs we want, and then write it to Couchbase:

[source,scala]
----
include::example$SparkSQL.scala[tag=subdoc1,indent=0]
----

Our DataFrame now looks something like:
```
__META_ID    | user.name          | user.age
-----------------------------------------
"docId1"     | "John Richardson"  | 29
"docId2"     | "Jane Doe"         | 34
```

Now write the transformed data back to KV using subdoc upsert.
As we have two rows in the DataFrame this will result in two sub-document KV mutateIn calls from the connector, and each will upsert two fields "user.name" and "user.age" into the target documents.

[source,scala]
----
include::example$SparkSQL.scala[tag=subdoc2,indent=0]
----

And we will end up with "docId1" containing JSON:
```
{
  "user": {
    "name": "John Richardson",
    "age": 29
  }
  // .. and the rest of the document, which will not have been modified
}
```
This is a very simple example of what is possible with sub-document.
See the https://docs.couchbase.com/scala-sdk/current/howtos/subdocument-operations.html[Scala SDK documentation on sub-document operations] for full details.


N.b. `remove` sub-document spec operations are a special case as they will ignore the provided value.
Hence any value can be used, except null, as Spark will automatically remove null columns before it passes the DataFrame to the connector.


=== DataFrame persistence performance tips
We strongly recommend using the KeyValue data source for persisting DataFrames.
This will automatically provide the best possible write performance.

But if the query data source is required, then we recommend:

* Partition the data before writing it.  (Each partition results in one INSERT or UPSERT SQL++ statement being executed by the connector.)
* Observe the Spark worker logs to see how long each query is taking and if timeouts are occurring.  Increase the partition count and/or the timeout value as needed.
* The multiple large SQL++ statements that can be generated by the connector with large datasets may fill query service's system:completed_requests table, leading to high query memory usage and potentially out-of-memory issues.  Consider disabling or increasing the threshold for this, following xref:https://docs.couchbase.com/server/current/n1ql/n1ql-manage/monitoring-n1ql-query.html#sys-completed-config[these docs].
* And standard recommendations for writing at scale: consider using separate nodes for query and KV; use disks that can support the throughput needed; use powerful enough nodes to support the throughput needed; ensure there is sufficient network bandwidth.

[#_datasets]
== Datasets
You can call `.as[Target]` on your `DataFrame` to turn it into typesafe counterpart (most of the time a case class).

(Note that Apache Spark only supports Datasets in Scala - there is no PySpark equivalent.)

Consider having the following case class:

[source,scala]
----
include::example$SparkSQL.scala[tag=caseclass,indent=0]
----

Make sure to import the implicits for the `SparkSession`:

[source,scala]
----
import spark.implicits._
----

You can now create a DataFrame as usual which can be turned into a Dataset:

[source,scala]
----
include::example$SparkSQL.scala[tag=ds,indent=0]
----

If you want to print all Airlines that start with "A" you can access the properties on the case class:

[source,scala]
----
include::example$SparkSQL.scala[tag=dsfetch,indent=0]

----

For more information on Datasets, please refer to the http://spark.apache.org/docs/latest/sql-programming-guide.html#datasets[Spark Dataset Docs^].

== Options

[#_query_options]
=== Query options
The available options for query DataFrame and Dataset operations:

.Query Options
[cols="1,1,1,1"]
|===
| PySpark | Scala & Java | Option | Default

| "bucket"
| QueryOptions.Bucket
| Name of a Couchbase bucket
| Mandatory unless xref:configuration.adoc#_optional_properties[implicitBucket is set]

| "scope"
| QueryOptions.Scope
| Name of a Couchbase scope
| Defaults to the default scope on the specified bucket.  Note xref:configuration.adoc#_optional_properties[implicitScope can be set in Spark config].

| "collection"
| QueryOptions.Collection
| Name of a Couchbase collection
| Defaults to the default collection on the specified scope.  Note xref:configuration.adoc#_optional_properties[implicitCollection can be set in Spark config].

| "timeout"
| QueryOptions.Timeout
| Overrides the default timeout.  The string must be parsable from a Scala Duration.
| 75 seconds

| "idFieldName"
| QueryOptions.IdFieldName
| Uses a different column when xref:_dataframe_persistence[persisting a DataFrame].
| "META_ID" column

| "filter"
| QueryOptions.Filter
| A SQL++ expression that will be interjected directly into the generated SQL++, e.g. `type = 'airport'`.
| None

| "partitionColumn"
"partitionLowerBound"
"partitionUpperBound"
"partitionCount"
| QueryOptions.PartitionColumn
QueryOptions.PartitionLowerBound
QueryOptions.PartitionUpperBound
QueryOptions.PartitionCount
| Control how xref:_dataframe_partitioning[manual DataFrame partitioning] is performed.
| None

| "scanConsistency"
| QueryOptions.ScanConsistency
| Valid options are "requestPlus" / QueryOptions.RequestPlusScanConsistency and "notBounded" / QueryOptions.NotBoundedScanConsistency.
| "notBounded"

| "inferLimit"
| QueryOptions.InferLimit
| Controls how many documents are initially sampled to perform xref:_schemas[schema inference].
| 1000

| "connectionIdentifier"
| QueryOptions.ConnectionIdentifier
| Allows a different configuration to be used than the default one.  See xref:configuration.adoc#_connecting_to_multiple_clusters[Connecting to multiple clusters].
| Default connection

| "outputCas"
| QueryOptions.OutputCas
| Adds a field to the DataFrame, containing each document's CAS value for use in optimistic concurrency control.  The field name is controlled by `QueryOptions.CasFieldName`.
| <does not output CAS>

| "casFieldName"
| QueryOptions.CasFieldName
| Controls the name of the field that is output by `QueryOptions.OutputCas`
| "__META_CAS"
|===

[#_enterprise_analytics_options]
=== Enterprise Analytics options
The available options for Enterprise Analytics DataFrame and Dataset operations:

.Enterprise Analytics Options
[cols="1,1,1,1"]
|===
| PySpark | Scala & Java | Option | Default

| "database"
| EnterpriseAnalyticsOptions.Database
| Name of an Enterprise Analytics database
| Mandatory

| "scope"
| EnterpriseAnalyticsOptions.Scope
| Name of an Enterprise Analytics scope
| Mandatory

| "collection"
| EnterpriseAnalyticsOptions.Collection
| Name of an Enterprise Analytics collection
| Mandatory

| "timeout"
| EnterpriseAnalyticsOptions.Timeout
| Overrides the default timeout.  The string must be parsable from a Scala Duration.
| 10 minutes

| "filter"
| EnterpriseAnalyticsOptions.Filter
| A SQL++ expression that will be interjected directly into the generated SQL++, e.g. `type = 'airport'`.
| None

| "scanConsistency"
| EnterpriseAnalyticsOptions.ScanConsistency
| Valid options are "requestPlus" / EnterpriseAnalyticsOptions.RequestPlusScanConsistency and "notBounded" / EnterpriseAnalyticsOptions.NotBoundedScanConsistency.
| "notBounded"

| "inferLimit"
| EnterpriseAnalyticsOptions.InferLimit
| Controls how many documents are initially sampled to perform xref:_schemas[schema inference].
| 1000
|===

[#_kv_options]
=== KeyValue options
The available options for query DataFrame and Dataset operations:

.KeyValue Options
[cols="1,1,1,1"]
|===
| PySpark | Scala & Java | Option | Default

| "bucket"
| KeyValueOptions.Bucket
| Name of a Couchbase bucket
| Mandatory unless xref:configuration.adoc#_optional_properties[implicitBucket is set]

| "scope"
| KeyValueOptions.Scope
| Name of a Couchbase scope
| Defaults to the default scope on the specified bucket.  Note xref:configuration.adoc#_optional_properties[implicitScope can be set in Spark config].

| "collection"
| KeyValueOptions.Collection
| Name of a Couchbase collection
| Defaults to the default collection on the specified scope.  Note xref:configuration.adoc#_optional_properties[implicitCollection can be set in Spark config].

| "timeout"
| KeyValueOptions.Timeout
| Overrides the default timeout.  The string must be parsable from a Scala Duration.
| 2.5 seconds for non-durable operations, 10 seconds for durable operations

| "idFieldName"
| KeyValueOptions.IdFieldName
| Uses a different column when xref:_dataframe_persistence[persisting a DataFrame].
| "META_ID" column

| "durability"
| KeyValueOptions.Durability
| Valid options are "none", "majority" / KeyValueOptions.MajorityDurability, "majorityAndPersistToActive" / KeyValueOptions.MajorityAndPersistToActiveDurability, and "PersistToMajority" / KeyValueOptions.PersistToMajorityDurability.
| "none"

| "connectionIdentifier"
| KeyValueOptions.ConnectionIdentifier
| Allows a different configuration to be used than the default one.  See xref:configuration.adoc#_connecting_to_multiple_clusters[Connecting to multiple clusters].
| Default connection

| "writeMode"
| KeyValueOptions.WriteMode
| Controls the write behavior, overriding the Spark SaveMode. The only valid option currently is KeyValueOptions.WriteModeReplace ("replace" for PySpark users).
| None (uses SaveMode)

| "casFieldName"
| KeyValueOptions.CasFieldName
| Both enables optimistic locking detection (CAS) for operations that support it, and specifies the field name containing CAS values.
| <CAS detection is disabled>>

| "errorBucket"
| KeyValueOptions.ErrorBucket
| Enable writing error documents to a given bucket if operations fail.
| None (operations fail the job)

| "errorScope"
| KeyValueOptions.ErrorScope
| Further customises KeyValueOptions.ErrorBucket to output to a particular scope.
| Default scope

| "errorCollection"
| KeyValueOptions.ErrorCollection
| Further customises KeyValueOptions.ErrorBucket to output to a particular collection.
| Default collection

| "errorHandler"
| KeyValueOptions.ErrorHandler
| Custom error handler class for handling operation failures. Must implement the appropriate interface.
| None (operations fail the job)
|===


[#_columnar_options]
=== Capella Columnar options
The available options for Capella Columnar DataFrame and Dataset operations:

.Capella Columnar Options
[cols="1,1,1,1"]
|===
| PySpark | Scala & Java | Option | Default

| "database"
| ColumnarOptions.Database
| Name of a Couchbase Columnar database
| Mandatory

| "scope"
| ColumnarOptions.Scope
| Name of a Couchbase Columnar scope
| Mandatory

| "collection"
| ColumnarOptions.Collection
| Name of a Couchbase Columnar collection
| Mandatory

| "timeout"
| ColumnarOptions.Timeout
| Overrides the default timeout.  The string must be parsable from a Scala Duration.
| 10 minutes

| "filter"
| ColumnarOptions.Filter
| A SQL++ expression that will be interjected directly into the generated SQL++, e.g. `type = 'airport'`.
| None

| "scanConsistency"
| ColumnarOptions.ScanConsistency
| Valid options are "requestPlus" / ColumnarOptions.RequestPlusScanConsistency and "notBounded" / ColumnarOptions.NotBoundedScanConsistency.
| "notBounded"

| "inferLimit"
| ColumnarOptions.InferLimit
| Controls how many documents are initially sampled to perform xref:_schemas[schema inference].
| 1000

| "connectionIdentifier"
| ColumnarOptions.ConnectionIdentifier
| Allows a different configuration to be used than the default one.  See xref:configuration.adoc#_connecting_to_multiple_clusters[Connecting to multiple clusters].
| Default connection
|===


== Aggregate Push Down

The following predicates are pushed down to the query, operational analytics, Enterprise Analytics, and Capella Columnar engines if possible:

- `MIN(field)`
- `MAX(field)`
- `COUNT(field)`
- `SUM(field)`
- `COUNT(*)`

They are supported both with and without grouping (`GROUP BY`).

For performance reasons, this feature is enabled by default, unless using xref:_dataframe_partitioning[manual partitioning].
If for some reason it should be disabled, the `PushDownAggregate` option can be used in which case Spark will handle the aggregations after receiving the results.
